#!/usr/bin/env python3
"""
Generate Figure 14 — Cost-of-Living Adjusted Benefit Adequacy.

Three-panel chart:
  Panel A: BAI vs COL-BAI side-by-side (housing-only vs full cost-of-living adjusted)
  Panel B: MIT Living Wage Gap — weekly dollar deficit below survival floor
  Panel C: Historical trend — BAI, COL-BAI, and Living Wage Coverage across 2010/2018/2026

Three-tier fallback:
  1. data/col_bai_results.json (generated by col_bai_engine.py)
  2. Hardcoded engine defaults (col_bai_engine.compute_col_bai on CSV data)
  3. Fully hardcoded values embedded below

Run: python generate_col_bai_figure.py
"""
import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

ROOT = Path(__file__).resolve().parent

# ── Brand palette ─────────────────────────────────────────────────────────────
BG, BG2, GRID = "#121212", "#1e1e1e", "#2a2a2a"
FG, MUTED     = "#e8e8e8", "#888888"
GREEN, LIME   = "#00FF41", "#BFFF00"
GOLD, CRIMSON = "#D4AF37", "#DC143C"
BLUE, ORANGE  = "#4aa8d8", "#F39C12"

OUT_PATH = ROOT / "figures" / "14_col_bai_comparison.png"

# ── Hardcoded fallback (Tier 3) ───────────────────────────────────────────────
FALLBACK = {
    "District of Columbia": {
        2010: {"bai": 0.945, "col_bai": 0.793, "mit_weekly": 663, "max_wba": 359, "living_wage_gap": 304, "coverage": 54.1},
        2018: {"bai": 0.965, "col_bai": 0.805, "mit_weekly": 825, "max_wba": 444, "living_wage_gap": 381, "coverage": 53.8},
        2026: {"bai": 0.854, "col_bai": 0.717, "mit_weekly": 1096, "max_wba": 444, "living_wage_gap": 652, "coverage": 40.5},
    },
    "Maryland": {
        2010: {"bai": 1.458, "col_bai": 1.372, "mit_weekly": 558, "max_wba": 430, "living_wage_gap": 128, "coverage": 77.1},
        2018: {"bai": 1.162, "col_bai": 1.078, "mit_weekly": 716, "max_wba": 430, "living_wage_gap": 286, "coverage": 60.1},
        2026: {"bai": 0.956, "col_bai": 0.884, "mit_weekly": 926, "max_wba": 430, "living_wage_gap": 496, "coverage": 46.4},
    },
    "Virginia": {
        2010: {"bai": 1.400, "col_bai": 1.375, "mit_weekly": 513, "max_wba": 378, "living_wage_gap": 135, "coverage": 73.7},
        2018: {"bai": 1.096, "col_bai": 1.066, "mit_weekly": 657, "max_wba": 378, "living_wage_gap": 279, "coverage": 57.5},
        2026: {"bai": 1.024, "col_bai": 0.990, "mit_weekly": 860, "max_wba": 430, "living_wage_gap": 430, "coverage": 50.0},
    },
}


def _load_results() -> dict | None:
    """Tier 1: load col_bai_results.json."""
    path = ROOT / "data" / "col_bai_results.json"
    if path.exists():
        try:
            with open(path) as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            pass
    return None


def _try_engine() -> dict | None:
    """Tier 2: run col_bai_engine directly."""
    try:
        sys.path.insert(0, str(ROOT))
        from col_bai_engine import run as run_engine
        import tempfile
        tmp = Path(tempfile.mktemp(suffix=".json"))
        result = run_engine(output_path=tmp)
        if tmp.exists():
            tmp.unlink()
        return result
    except Exception as e:
        print(f"  Engine fallback failed: {e}")
        return None


def _parse_results(results: dict) -> dict:
    """Parse JSON results into nested {jurisdiction: {year: metrics}} dict."""
    parsed: dict[str, dict[int, dict]] = {}
    for row in results.get("data", []):
        jur = row.get("jurisdiction")
        yr = row.get("year")
        if jur and yr:
            if jur not in parsed:
                parsed[jur] = {}
            parsed[jur][yr] = {
                "bai":             row.get("bai", 0),
                "col_bai":         row.get("col_bai", 0),
                "mit_weekly":      row.get("mit_living_wage_weekly", 0),
                "max_wba":         row.get("max_wba", 0),
                "living_wage_gap": row.get("living_wage_gap", 0),
                "coverage":        row.get("living_wage_coverage_pct", 0),
            }
    return parsed


def _style_ax(ax, title: str):
    ax.set_facecolor(BG2)
    ax.tick_params(colors=FG, labelsize=8)
    ax.xaxis.label.set_color(FG)
    ax.yaxis.label.set_color(FG)
    for spine in ax.spines.values():
        spine.set_edgecolor(GRID)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.set_title(title, color=FG, fontsize=9, fontweight="bold", loc="left", pad=6)
    ax.yaxis.grid(True, color=GRID, linewidth=0.5, linestyle="--")
    ax.set_axisbelow(True)


def make_figure(data: dict[str, dict[int, dict]]):
    years = [2010, 2018, 2026]
    jurisdictions = ["District of Columbia", "Maryland", "Virginia"]
    short = {"District of Columbia": "DC", "Maryland": "MD", "Virginia": "VA"}
    colors_bai    = [CRIMSON, GOLD, LIME]     # per jurisdiction
    colors_col    = ["#8B0000", "#B8860B", "#006400"]  # darker versions for COL-BAI

    fig, axes = plt.subplots(1, 3, figsize=(15, 5.5))
    fig.patch.set_facecolor(BG)

    # ── Panel A: BAI vs COL-BAI (2026 only) ──────────────────────────────────
    ax = axes[0]
    _style_ax(ax, "A — BAI vs COL-BAI (2026)")

    x = np.arange(len(jurisdictions))
    w = 0.35
    for i, (jur, cb, cc) in enumerate(zip(jurisdictions, colors_bai, colors_col)):
        yr_data = data.get(jur, {}).get(2026, {})
        bai_val = yr_data.get("bai", 0)
        col_val = yr_data.get("col_bai", 0)
        b1 = ax.bar(x[i] - w/2, bai_val, w, color=cb, alpha=0.85, label=f"{short[jur]} BAI")
        b2 = ax.bar(x[i] + w/2, col_val, w, color=cc, alpha=0.85, label=f"{short[jur]} COL-BAI")
        ax.text(x[i] - w/2, bai_val + 0.01, f"{bai_val:.2f}", ha="center", va="bottom",
                fontsize=7.5, color=FG, fontweight="bold")
        ax.text(x[i] + w/2, col_val + 0.01, f"{col_val:.2f}", ha="center", va="bottom",
                fontsize=7.5, color=FG, fontweight="bold")

    ax.axhline(1.0, color=GREEN, linewidth=1.2, linestyle="--", alpha=0.8)
    ax.text(2.6, 1.015, "threshold", color=GREEN, fontsize=7, alpha=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels([short[j] for j in jurisdictions], fontsize=9)
    ax.set_ylabel("Index (1.0 = benefit covers cost)", fontsize=8, color=MUTED)
    ax.set_ylim(0, 1.25)

    # Legend
    legend_handles = [
        mpatches.Patch(color=CRIMSON, alpha=0.85, label="BAI (housing only)"),
        mpatches.Patch(color="#8B0000", alpha=0.85, label="COL-BAI (full basket, BEA RPP)"),
    ]
    ax.legend(handles=legend_handles, fontsize=7, loc="upper right",
              facecolor=BG2, edgecolor=GRID, labelcolor=FG)

    ax.text(0, -0.18,
        "BAI = Max WBA ÷ Weekly Housing  |  COL-BAI = Max WBA ÷ (Weekly Housing × BEA RPP/100)\n"
        "Source: BEA Regional Price Parities 2022; DOL/State benefit schedules; HUD FMR",
        transform=ax.transAxes, color="#555555", fontsize=7, va="top")

    # ── Panel B: Living Wage Gap (all years) ──────────────────────────────────
    ax = axes[1]
    _style_ax(ax, "B — Weekly Living Wage Gap (vs MIT 1-Adult Baseline)")

    x = np.arange(len(years))
    w = 0.25
    for i, (jur, cc) in enumerate(zip(jurisdictions, colors_bai)):
        gaps = [abs(data.get(jur, {}).get(yr, {}).get("living_wage_gap", 0)) for yr in years]
        offset = (i - 1) * w
        bars = ax.bar(x + offset, gaps, w, color=cc, alpha=0.85, label=short[jur])
        for bar, val in zip(bars, gaps):
            if val > 0:
                ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 3,
                        f"${val:.0f}", ha="center", va="bottom", fontsize=7, color=FG)

    ax.set_xticks(x)
    ax.set_xticklabels([str(y) for y in years], fontsize=9)
    ax.set_ylabel("$/week below survival floor", fontsize=8, color=MUTED)
    ax.legend(fontsize=8, facecolor=BG2, edgecolor=GRID, labelcolor=FG)

    ax.text(0, -0.18,
        "Living Wage Gap = MIT Living Wage (1 adult, weekly) − Max Weekly Benefit\n"
        "Source: MIT Living Wage Calculator (livingwage.mit.edu); DOL/State schedules",
        transform=ax.transAxes, color="#555555", fontsize=7, va="top")

    # ── Panel C: Coverage trend (all three years) ─────────────────────────────
    ax = axes[2]
    _style_ax(ax, "C — Living Wage Coverage Trend (% of survival floor)")

    for jur, cc in zip(jurisdictions, colors_bai):
        coverage = [data.get(jur, {}).get(yr, {}).get("coverage", 0) for yr in years]
        ax.plot(years, coverage, color=cc, marker="o", linewidth=2,
                markersize=6, label=short[jur])
        for yr, val in zip(years, coverage):
            ax.text(yr, val + 1.5, f"{val:.0f}%", ha="center", va="bottom",
                    fontsize=7.5, color=FG)

    ax.axhline(100, color=GREEN, linewidth=1, linestyle="--", alpha=0.6)
    ax.text(2019, 101.5, "100% = covers survival", color=GREEN, fontsize=7, alpha=0.7)
    ax.set_xticks(years)
    ax.set_xticklabels([str(y) for y in years])
    ax.set_ylabel("% of MIT Living Wage covered", fontsize=8, color=MUTED)
    ax.set_ylim(0, 115)
    ax.legend(fontsize=8, facecolor=BG2, edgecolor=GRID, labelcolor=FG)

    ax.text(0, -0.18,
        "Coverage = (Max WBA / MIT Living Wage Weekly) × 100\n"
        "MIT Living Wage: 2010/2018 retrospective estimates; 2024 published values",
        transform=ax.transAxes, color="#555555", fontsize=7, va="top")

    # ── Overall title ─────────────────────────────────────────────────────────
    fig.suptitle(
        "Figure 14 — The Real Cost Gap: COL-Adjusted Adequacy & Living Wage Coverage",
        color=GREEN, fontsize=13, fontweight="bold", family="monospace",
        x=0.02, ha="left", y=1.01,
    )
    fig.text(
        0.02, -0.01,
        "BAI measures whether the check covers rent alone. COL-BAI adjusts for the full consumer basket. "
        "Living Wage Coverage shows what fraction of actual survival costs the check provides.\n"
        "DC's COL-BAI = 0.717 means the benefit covers 72% of the COL-adjusted housing equivalent — "
        "and only 41% of what MIT calculates as survival-level income.",
        color=MUTED, fontsize=8, ha="left",
    )

    plt.tight_layout(rect=[0, 0.04, 1, 0.98])
    OUT_PATH.parent.mkdir(exist_ok=True)
    plt.savefig(OUT_PATH, facecolor=BG, bbox_inches="tight", dpi=150)
    plt.close()
    print(f"  Saved: {OUT_PATH}")


def main():
    print("=" * 60)
    print("GENERATE FIGURE 14 — COL-BAI COMPARISON")
    print("=" * 60)

    # Tier 1: cached results
    results = _load_results()
    if results:
        print("  [Tier 1] Loaded col_bai_results.json")
        data = _parse_results(results)
    else:
        # Tier 2: run engine
        print("  [Tier 2] Running col_bai_engine directly...")
        engine_out = _try_engine()
        if engine_out:
            data = _parse_results(engine_out)
        else:
            # Tier 3: hardcoded
            print("  [Tier 3] Using hardcoded fallback values")
            data = FALLBACK

    make_figure(data)
    print("Done.")


if __name__ == "__main__":
    main()
